# Generated by Django 5.0.6 on 2024-07-08 08:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_rename_orders_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(verbose_name=datetime.datetime(2024, 7, 8, 8, 5, 48, 41572)),
        ),
    ]
