# Generated by Django 5.0.7 on 2024-07-12 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_user_email_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
