# Generated by Django 5.0.7 on 2024-07-12 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
